### ISSUE TITLE
No additional files

### ISSUE THREAD

**Issue by thrichter** [Xembalo/hansol-aio-dashboard#1]
Hi,

Ich habe gerade dein sehr cooles Projekt gefunden und wollte es mal bei mir aufsetzen.
Der im Text erwähnte Ordner mit dem Batch- und Database Script sehe ich nirgendwo.
Könntest du die Dateien noch zur Verfügung stellen.

Danke,
Thorsten

**Comment by Xembalo** [comment]
Hallo Thorsten,

hatte das Thema etwas aus den Augen verloren, das lief einfach so nebenher. Sorry. Habe die Datei jetzt hochgeladen.

**Comment by nriewenh** [comment]
Hi, ich versuche dein Projekt gerade in mein Home Assistant einzubinden. Allerdings kann ich die Dateien nicht über Hacs einbinden
